server:
  port: ${PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  firebase:
    bucket: ${FIREBASE_BUCKET}
    credentials: ${FIREBASE_CREDENTIALS_BASE64}

  logging:
    level:
      root: INFO
      org.springframework: DEBUG
  spring:
    main:
      log-startup-info: true

